version: '3.8'
services:
# Nuxt publication
  th2-docs-writer:
    container_name: writer.th2-docs
    build:
      context: .
      dockerfile: Dockerfile.writer
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
