<template>
	<v-container class="space-bottom px-md-12 px-4">
		<article v-if="!hideDoc">
			<GitHubRepoInfo />
			<recommendations v-if="doc.read_before && doc.read_before.length"
											 class="my-4" :items="doc.read_before" >
				<div>Before you start take a look at:</div>
			</recommendations>
			<VueRemarkContent class="vue-remark"/>
			<prev-next class="my-4" v-if="doc.prev || doc.next"
								 :prev-title="doc.prev ? doc.prev.title : ''"
								 :next-title="doc.next ? doc.next.title : ''"
								 :prev-link="doc.prev ? doc.prev.link : ''"
								 :next-link="doc.next ? doc.next.link : ''"
								 :prev-icon="doc.prev ? doc.prev.icon : ''"
								 :next-icon="doc.next ? doc.next.icon : ''">
			</prev-next>
			<recommendations v-if="doc.continue_learning && doc.continue_learning.length"
											 class="my-4" :items="doc.continue_learning" >
				<div>Continue learning:</div>
			</recommendations>
		</article>
		<nav v-else class="vue-remark">
			<h1>{{doc.title}}</h1>
			<AutogeneratedContent />
		</nav>
	</v-container>
</template>

<script>
import '~/assets/doc-article.scss'
import GitHubRepoInfo from "~/components/content/GitHubRepoInfo";
import AutogeneratedContent from "./AutogeneratedContent.vue";
export default {
	props: {
		doc: Object,
		hideDoc: Boolean
	},
	name: "Article",
	components: {
		GitHubRepoInfo, AutogeneratedContent
	}
}
</script>

<style  lang="scss">
.space-bottom {
	margin-bottom: 50vh;
}
</style>
