<template>
	<div v-if="currentPage">
		<v-list-item v-for="node in currentPage.children" :key="node.path"
						:to="node.path" class="rounded v-sheet--outlined my-2" >
			<v-list-item-icon>
				<v-icon color="primary">mdi-file-document-outline</v-icon>
			</v-list-item-icon>
			<v-list-item-content>
				<v-list-item-title class="font-weight-bold">
					{{node.title}}
				</v-list-item-title>
			</v-list-item-content>
		</v-list-item>
	</div>
</template>

<script lang="ts">
import Vue from "vue";
import {mapGetters} from "vuex";
import {TreeNode} from "../../plugins/gridsome/plugin/content-tree/types";

export default Vue.extend({
	name: "AutogeneratedContent",
	computed: {
		...mapGetters(['currentPage'])
	}
})
</script>

<style scoped>
</style>
