name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
#  schedule:
#    - cron: "0 3 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
      ALGOLIA_WRITE_API_KEY: ${{ secrets.ALGOLIA_WRITE_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Installing packages
        run: npm ci

#      - name: Compile plugins
#        run: npm run compile-plugins

      - name: Build Gridsome site
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/master'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: dist
          commit_message: 'Automatic build: ${{ github.event.head_commit.message }}'
