<template>
	<nav v-if="currentNode">
		<v-list-item v-for="node in currentNode.children" :key="node.path"
						:to="node.path" class="rounded v-sheet--outlined my-2" >
			<v-list-item-icon>
				<v-icon color="primary">mdi-file-document-outline</v-icon>
			</v-list-item-icon>
			<v-list-item-content>
				<v-list-item-title class="font-weight-bold">
					{{node.title}}
				</v-list-item-title>
			</v-list-item-content>
		</v-list-item>
	</nav>
</template>

<script lang="ts">
import Vue from "vue";
import {mapGetters} from "vuex";
import {TreeNode} from "../../plugins/gridsome/plugin/content-tree/types";

export default Vue.extend({
	name: "AutogeneratedContent",
	computed: {
		...mapGetters(['currentTree']),
		currentNode(){
			const searchNode = (tree: TreeNode[]): TreeNode | undefined => {
				let foundNode = undefined
				for (let node of tree) {
					if (node.path.startsWith(this.$route.path))
						return node
					else foundNode = searchNode(node.children)
				}
				return foundNode
			}
			return searchNode(this.currentTree)
		}
	}
})
</script>

<style scoped>
</style>
